package com.test;

import java.math.BigDecimal;
import java.util.Date;

public class BusinessInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_code
     *
     * @mbggenerated
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_name
     *
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.login_password
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.phone_account
     *
     * @mbggenerated
     */
    private String phoneAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.phone_password
     *
     * @mbggenerated
     */
    private String phonePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.aliPay_poundage
     *
     * @mbggenerated
     */
    private BigDecimal alipayPoundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.wechat_poundage
     *
     * @mbggenerated
     */
    private BigDecimal wechatPoundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.min_amount
     *
     * @mbggenerated
     */
    private BigDecimal minAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.max_amount
     *
     * @mbggenerated
     */
    private BigDecimal maxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.id
     *
     * @return the value of business_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.id
     *
     * @param id the value for business_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_code
     *
     * @return the value of business_info.business_code
     *
     * @mbggenerated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_code
     *
     * @param businessCode the value for business_info.business_code
     *
     * @mbggenerated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_name
     *
     * @return the value of business_info.business_name
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_name
     *
     * @param businessName the value for business_info.business_name
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.login_password
     *
     * @return the value of business_info.login_password
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.login_password
     *
     * @param loginPassword the value for business_info.login_password
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.phone_account
     *
     * @return the value of business_info.phone_account
     *
     * @mbggenerated
     */
    public String getPhoneAccount() {
        return phoneAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.phone_account
     *
     * @param phoneAccount the value for business_info.phone_account
     *
     * @mbggenerated
     */
    public void setPhoneAccount(String phoneAccount) {
        this.phoneAccount = phoneAccount == null ? null : phoneAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.phone_password
     *
     * @return the value of business_info.phone_password
     *
     * @mbggenerated
     */
    public String getPhonePassword() {
        return phonePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.phone_password
     *
     * @param phonePassword the value for business_info.phone_password
     *
     * @mbggenerated
     */
    public void setPhonePassword(String phonePassword) {
        this.phonePassword = phonePassword == null ? null : phonePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.aliPay_poundage
     *
     * @return the value of business_info.aliPay_poundage
     *
     * @mbggenerated
     */
    public BigDecimal getAlipayPoundage() {
        return alipayPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.aliPay_poundage
     *
     * @param alipayPoundage the value for business_info.aliPay_poundage
     *
     * @mbggenerated
     */
    public void setAlipayPoundage(BigDecimal alipayPoundage) {
        this.alipayPoundage = alipayPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.wechat_poundage
     *
     * @return the value of business_info.wechat_poundage
     *
     * @mbggenerated
     */
    public BigDecimal getWechatPoundage() {
        return wechatPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.wechat_poundage
     *
     * @param wechatPoundage the value for business_info.wechat_poundage
     *
     * @mbggenerated
     */
    public void setWechatPoundage(BigDecimal wechatPoundage) {
        this.wechatPoundage = wechatPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.min_amount
     *
     * @return the value of business_info.min_amount
     *
     * @mbggenerated
     */
    public BigDecimal getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.min_amount
     *
     * @param minAmount the value for business_info.min_amount
     *
     * @mbggenerated
     */
    public void setMinAmount(BigDecimal minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.max_amount
     *
     * @return the value of business_info.max_amount
     *
     * @mbggenerated
     */
    public BigDecimal getMaxAmount() {
        return maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.max_amount
     *
     * @param maxAmount the value for business_info.max_amount
     *
     * @mbggenerated
     */
    public void setMaxAmount(BigDecimal maxAmount) {
        this.maxAmount = maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.create_time
     *
     * @return the value of business_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.create_time
     *
     * @param createTime the value for business_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.update_time
     *
     * @return the value of business_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.update_time
     *
     * @param updateTime the value for business_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}