package com.test;

import com.test.BusinessInfo;

public interface BusinessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated
     */
    int insert(BusinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated
     */
    int insertSelective(BusinessInfo record);
}