package com.test;

import com.test.CodeMan;

public interface CodeManMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_man
     *
     * @mbggenerated
     */
    int insert(CodeMan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_man
     *
     * @mbggenerated
     */
    int insertSelective(CodeMan record);
}