package com.test;

import java.math.BigDecimal;
import java.util.Date;

public class CodeMan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.man_code
     *
     * @mbggenerated
     */
    private String manCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.man_name
     *
     * @mbggenerated
     */
    private String manName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.phone_account
     *
     * @mbggenerated
     */
    private String phoneAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.phone_password
     *
     * @mbggenerated
     */
    private String phonePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.credit_quota
     *
     * @mbggenerated
     */
    private BigDecimal creditQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.surplus_quota
     *
     * @mbggenerated
     */
    private BigDecimal surplusQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.receivables
     *
     * @mbggenerated
     */
    private BigDecimal receivables;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.business_code
     *
     * @mbggenerated
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_man.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.id
     *
     * @return the value of code_man.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.id
     *
     * @param id the value for code_man.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.man_code
     *
     * @return the value of code_man.man_code
     *
     * @mbggenerated
     */
    public String getManCode() {
        return manCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.man_code
     *
     * @param manCode the value for code_man.man_code
     *
     * @mbggenerated
     */
    public void setManCode(String manCode) {
        this.manCode = manCode == null ? null : manCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.man_name
     *
     * @return the value of code_man.man_name
     *
     * @mbggenerated
     */
    public String getManName() {
        return manName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.man_name
     *
     * @param manName the value for code_man.man_name
     *
     * @mbggenerated
     */
    public void setManName(String manName) {
        this.manName = manName == null ? null : manName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.phone_account
     *
     * @return the value of code_man.phone_account
     *
     * @mbggenerated
     */
    public String getPhoneAccount() {
        return phoneAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.phone_account
     *
     * @param phoneAccount the value for code_man.phone_account
     *
     * @mbggenerated
     */
    public void setPhoneAccount(String phoneAccount) {
        this.phoneAccount = phoneAccount == null ? null : phoneAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.phone_password
     *
     * @return the value of code_man.phone_password
     *
     * @mbggenerated
     */
    public String getPhonePassword() {
        return phonePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.phone_password
     *
     * @param phonePassword the value for code_man.phone_password
     *
     * @mbggenerated
     */
    public void setPhonePassword(String phonePassword) {
        this.phonePassword = phonePassword == null ? null : phonePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.credit_quota
     *
     * @return the value of code_man.credit_quota
     *
     * @mbggenerated
     */
    public BigDecimal getCreditQuota() {
        return creditQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.credit_quota
     *
     * @param creditQuota the value for code_man.credit_quota
     *
     * @mbggenerated
     */
    public void setCreditQuota(BigDecimal creditQuota) {
        this.creditQuota = creditQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.surplus_quota
     *
     * @return the value of code_man.surplus_quota
     *
     * @mbggenerated
     */
    public BigDecimal getSurplusQuota() {
        return surplusQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.surplus_quota
     *
     * @param surplusQuota the value for code_man.surplus_quota
     *
     * @mbggenerated
     */
    public void setSurplusQuota(BigDecimal surplusQuota) {
        this.surplusQuota = surplusQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.receivables
     *
     * @return the value of code_man.receivables
     *
     * @mbggenerated
     */
    public BigDecimal getReceivables() {
        return receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.receivables
     *
     * @param receivables the value for code_man.receivables
     *
     * @mbggenerated
     */
    public void setReceivables(BigDecimal receivables) {
        this.receivables = receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.business_code
     *
     * @return the value of code_man.business_code
     *
     * @mbggenerated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.business_code
     *
     * @param businessCode the value for code_man.business_code
     *
     * @mbggenerated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.status
     *
     * @return the value of code_man.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.status
     *
     * @param status the value for code_man.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.create_time
     *
     * @return the value of code_man.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.create_time
     *
     * @param createTime the value for code_man.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_man.update_time
     *
     * @return the value of code_man.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_man.update_time
     *
     * @param updateTime the value for code_man.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}