package com.test;

import com.test.PayAccount;

public interface PayAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated
     */
    int insert(PayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated
     */
    int insertSelective(PayAccount record);
}