package com.test;

import java.util.Date;

public class PayAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.pay_account
     *
     * @mbggenerated
     */
    private String payAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.account_type
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.code_man
     *
     * @mbggenerated
     */
    private String codeMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.online_time
     *
     * @mbggenerated
     */
    private Date onlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.offline_time
     *
     * @mbggenerated
     */
    private Date offlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.id
     *
     * @return the value of pay_account.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.id
     *
     * @param id the value for pay_account.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.pay_account
     *
     * @return the value of pay_account.pay_account
     *
     * @mbggenerated
     */
    public String getPayAccount() {
        return payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.pay_account
     *
     * @param payAccount the value for pay_account.pay_account
     *
     * @mbggenerated
     */
    public void setPayAccount(String payAccount) {
        this.payAccount = payAccount == null ? null : payAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.account_type
     *
     * @return the value of pay_account.account_type
     *
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.account_type
     *
     * @param accountType the value for pay_account.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.code_man
     *
     * @return the value of pay_account.code_man
     *
     * @mbggenerated
     */
    public String getCodeMan() {
        return codeMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.code_man
     *
     * @param codeMan the value for pay_account.code_man
     *
     * @mbggenerated
     */
    public void setCodeMan(String codeMan) {
        this.codeMan = codeMan == null ? null : codeMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.user_name
     *
     * @return the value of pay_account.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.user_name
     *
     * @param userName the value for pay_account.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.status
     *
     * @return the value of pay_account.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.status
     *
     * @param status the value for pay_account.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.online_time
     *
     * @return the value of pay_account.online_time
     *
     * @mbggenerated
     */
    public Date getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.online_time
     *
     * @param onlineTime the value for pay_account.online_time
     *
     * @mbggenerated
     */
    public void setOnlineTime(Date onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.offline_time
     *
     * @return the value of pay_account.offline_time
     *
     * @mbggenerated
     */
    public Date getOfflineTime() {
        return offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.offline_time
     *
     * @param offlineTime the value for pay_account.offline_time
     *
     * @mbggenerated
     */
    public void setOfflineTime(Date offlineTime) {
        this.offlineTime = offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.level
     *
     * @return the value of pay_account.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.level
     *
     * @param level the value for pay_account.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.create_time
     *
     * @return the value of pay_account.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.create_time
     *
     * @param createTime the value for pay_account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}